config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :audits
    resources :reagents
    resources :reagent_amounts
    resources :reagent_categories
    resources :recipes
    resources :reference_bottles
    resources :cocktail_families

    root to: "users#index"
  end
  devise_for :users
  root to: 'home#index'
  resources :recipes
  resources :reagents do
    post :refill
    post :empty
    get :add_to_list, to: 'reagents#shopping_list_show'
  end
  resources :bulk_reagents, only: [:index, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails do
    post :delete
    get :pre_make_drink
    post :make_drink
    post :toggle_favorite
    post :propose_to_share
    post :make_permanent
    get :nearest_neighbors
  end

  resources :cocktail_families, only: [:show, :create, :update]

  resources :drink_making, only: [:show, :update] do
  end

  # TODO: rename these routes
  scope :cocktails_async do
    get :drink_builder, to: 'cocktails#drink_builder'
  end

  resources :shared_cocktails, only: [:index, :show, :destroy] do
    post :add_to_account
    post :promote_to_shared
  end

  resources :shopping, only: [:index, :show, :new, :create, :destroy, :edit] do
    get :list
    post :purchase
    patch :list, to: 'shopping#update'
  end
  scope :shopping do
    put :add_to_list, to: 'shopping#add_to_list'
  end

  resources :shopping_list_items, only: [:destroy]

  resources :audits, only: [:index, :show, :update, :destroy]

  resources :reagent_categories, only: [:index, :show, :edit, :update, :new, :create]

  resources :reference_bottles, only: [:new, :create, :edit, :update, :destroy]
end

app/models/reagent_category.rb
# == Schema Information
#
# Table name: reagent_categories
#
#  id                             :bigint           not null, primary key
#  name                           :string
#  created_at                     :datetime         not null
#  updated_at                     :datetime         not null
#  description                    :text
#  external_id                    :string           not null
#  override_dimension_external_id :string
#
# Indexes
#
#  index_reagent_categories_on_external_id  (external_id) UNIQUE
#  index_reagent_categories_on_name         (name) UNIQUE
#
class ReagentCategory < ApplicationRecord
  has_many :reference_bottles, dependent: :destroy

  def reagents(current_user)
    Reagent.for_user(current_user).with_tags(external_id)
  end

  def reagent_amounts(current_user)
    ReagentAmount.for_user(current_user).with_tags(external_id)
  end

  def dimension
    if override_dimension_external_id.present?
      return ReagentCategory.find_by(external_id: override_dimension_external_id).id
    end

    id
  end
end

app/controllers/admin/reagent_categories_controller.rb
module Admin
  class ReagentCategoriesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/reagent_categories_controller.rb
class ReagentCategoriesController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :new, :create]
  before_action :validate_admin!, only: [:edit, :update, :new, :create]

  before_action :redirect_non_existant_categories, only: [:show]

  def index
    search_term = search_params['search_term']

    if search_term.present? && search_term.size > 0
      @categories = ReagentCategory.where('name ILIKE ?', "%#{search_term}%").order(:name)
    else
      @categories = ReagentCategory.all.order(:name)
    end

    @reagents_resolver = ReagentResolver.new(current_user)
    @reagents_resolver.register_tags(@categories.pluck(:external_id))
  end

  def show
    @category = find_by_external_id_or_pk(params[:id])
    @reference_bottles = @category.reference_bottles

    if user_signed_in?
      @cocktails = Recipe.for_user_or_shared(current_user).by_tag(@category.external_id).reorder(:name).page(params[:page])
      @availability = CocktailAvailabilityService.new(@cocktails, current_user)
    else
      @cocktails = Recipe.for_user(nil).by_tag(@category.external_id).page(params[:page]).reorder(:name)
    end
  end

  def edit
    @category = find_by_external_id_or_pk(params[:id])
  end

  def new
    @category = ReagentCategory.new
  end

  def create
    @category = ReagentCategory.new(update_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "#{@category.external_id} was successfully created" }
      else
        format.html { render :new, status: :unprocessable_entity, alert: "#{@category.external_id} could not be created" }
      end
    end
  end

  def update
    @category = find_by_external_id_or_pk(params[:id])
    params = update_params

    # need to find all references to this category and rewrite them
    ReagentCategory.transaction do
      old_external_id = @category.external_id

      ReagentAmount.with_tags([old_external_id]).each do |amount|
        amount.tags.map! { |t| t == old_external_id ? params[:external_id] : t }
        amount.save!
      end

      Reagent.with_tags([old_external_id]).each do |reagent|
        reagent.tags.map! { |t| t == old_external_id ? params[:external_id] : t }
        reagent.save!
      end

      @category.update!(params)
    end

    respond_to do |format|
      format.html { redirect_to @category, notice: "#{@category.external_id} updated!"}
    end
  end

  def find_by_external_id_or_pk(id)
    begin
      ReagentCategory.find(Integer(id))
    rescue ArgumentError
      ReagentCategory.find_by(external_id: params[:id])
    end
  end

  private

  def update_params
    params.require(:reagent_category).permit(:name, :description, :external_id).tap do |p|
      p[:external_id] = Lib.to_external_id(p[:external_id])
    end
  end

  def search_params
    params.permit(:search_term)
  end

  def redirect_non_existant_categories
    redirect_to new_reagent_category_path, notice: "#{params[:id]} doesn't exist. You'll need to create it to move forward" unless find_by_external_id_or_pk(params[:id]).present?
  end
end

app/views/reagent_categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <div class="field mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :external_id, class: "form-label" %>
    <%= form.text_field :external_id, class: "form-control" %>
  </div>

  <div class="actions mb-3">
    <%= form.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/reagent_categories/edit.html.erb
<main>
  <div class="container">
    <%= form_with(model: @category) do |form| %>
      <div class="field mb-3">
        <%= form.label :name, class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="field mb-3">
        <%= form.label :description, class: "form-label" %>
        <%= form.text_field :description, class: "form-control" %>
      </div>

      <div class="field mb-3">
        <%= form.label :external_id, class: "form-label" %>
        <%= form.text_field :external_id, class: "form-control" %>
      </div>

      <div class="actions mb-3">
        <%= form.submit nil, class: "btn btn-primary" %>
      </div>
    <% end %>

    <%= link_to 'Back', reagent_categories_path, class: "btn btn-danger" %>
  </div>
</main>

app/views/reagent_categories/index.html.erb
<% content_for :per_page_js do %>
  <%= javascript_pack_tag "reagent_categories_index", "data-turbo-track": 'reload' %>
<% end %>
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-2">
        <%= form_with(url: "/reagent_categories", method: "GET") do |form| %>
          <div class="field mb-1">
            <%= form.label :search_term, class: "form-label" %>
            <%= form.text_field :search_term, class: "form-control", value: params['search_term'] %>
          </div>

          <div class="action mb-1">
            <%= form.submit "Search", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
      <div class="col-sm-10">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th>Category Name</th>
                <th>Show</th>
                <th>Reagents</th>
              </tr>
            </thead>
            <tbody>
              <% @categories.each do |category| %>
                <tr>
                  <td><%= category.name %></td>
                  <td><%= link_to "Details", reagent_category_path(category), class: "btn btn-outline-info" %></td>
                  <td>
                    <% if @reagents_resolver.reagents(category.external_id).present? %>
                      <table class="table">
                        <thead>
                          <tr>
                            <th>name</th>
                            <th>Current Volume</th>
                            <th>Max Volume</th>
                            <th>Show</th>
                          </tr>
                        </thead>
                        <tbody>
                        <% @reagents_resolver.reagents(category.external_id).each do |reagent| %>
                          <tr id="reagent_<%= reagent.id %>">
                            <td><%= reagent.name.titleize %></td>
                            <td data-volume-row><%= reagent.current_volume %></td>
                            <td><%= reagent.max_volume %></td>
                            <td><%= link_to "Details", reagent_path(reagent), class: "btn btn-outline-info" %></td>
                          </tr>
                        <% end %>
                        </tbody>
                      </table>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <% if current_user.present? && current_user.admin? %>
      <%= link_to 'New', new_reagent_category_path, class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</main>

app/views/reagent_categories/new.html.erb
<main>
  <div class="container">
    <%= render 'form', category: @category %>

    <%= link_to 'Back', reagent_categories_path, class: "btn btn-danger" %>
  </div>
</main>

app/views/reagent_categories/show.html.erb
<% content_for :per_page_js do %>
  <%= javascript_pack_tag "reagent_categories_show", "data-turbo-track": 'reload' %>
<% end %>
<main>
  <div class="container">
    <%= render 'shared/notice' %>

    <p>
      <strong>Name:</strong>
      <span><%= @category.name %></span>
    </p>

    <p>
      <strong>External Id:</strong>
      <span><samp><%= @category.external_id %></samp></span>
    </p>

    <% if current_user.present? && current_user.admin? %>
    <%= link_to 'Edit Category', edit_reagent_category_path(@category), class: "btn btn-primary" %>
    <% end %>
    <hr>

    <% if user_signed_in? %>
    <strong>Your bottles in this Category</strong>
    <div class="row">
      <div class="col table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th>name</th>
              <th>Current Volume</th>
              <th>Max Volume</th>
              <th>Show</th>
            </tr>
          </thead>
          <tbody>
          <% @category.reagents(current_user).real.each do |reagent| %>
            <tr id="reagent_<%= reagent.id %>">
              <td><%= reagent.name %></td>
              <td data-volume-row><%= reagent.current_volume %></td>
              <td><%= reagent.max_volume %></td>
              <td><%= link_to "Details", reagent_path(reagent), class: "btn btn-outline-info" %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <hr>
    <% end %>

    <strong>Cocktails which use this category</strong>
    <%= render 'shared/cocktails_table', cocktails: @cocktails, read_only: false, render_counts: user_signed_in? %>

    <hr>
    <strong>Reference Bottles in this category</strong>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Image</th>
            <th>Description</th>
            <th>
          </tr>
        </thead>
        <tbody>
          <% @reference_bottles.each do |bottle| %>
            <tr>
              <td><%= bottle.name %></td>
              <td><img src=<%= bottle.main_image_url %> class="img-fluid img-thumbail" style="max-width: 10rem" ></td>
              <td><%= bottle.description %></td>
              <td><%= link_to "Edit", edit_reference_bottle_path(bottle), class: "btn btn-info" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <% if current_user.present? && current_user.admin? %>
    <%= link_to 'Add Reference Bottle', new_reference_bottle_path(reagent_category: @category), class: "btn btn-primary" %>
    <% end %>

  </div>
</main>