config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :audits
    resources :reagents
    resources :reagent_amounts
    resources :reagent_categories
    resources :recipes
    resources :reference_bottles
    resources :cocktail_families

    root to: "users#index"
  end
  devise_for :users
  root to: 'home#index'
  resources :recipes
  resources :reagents do
    post :refill
    post :empty
    get :add_to_list, to: 'reagents#shopping_list_show'
  end
  resources :bulk_reagents, only: [:index, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails do
    post :delete
    get :pre_make_drink
    post :make_drink
    post :toggle_favorite
    post :propose_to_share
    post :make_permanent
    get :nearest_neighbors
  end

  resources :cocktail_families, only: [:show, :create, :update]

  resources :drink_making, only: [:show, :update] do
  end

  # TODO: rename these routes
  scope :cocktails_async do
    get :drink_builder, to: 'cocktails#drink_builder'
  end

  resources :shared_cocktails, only: [:index, :show, :destroy] do
    post :add_to_account
    post :promote_to_shared
  end

  resources :shopping, only: [:index, :show, :new, :create, :destroy, :edit] do
    get :list
    post :purchase
    patch :list, to: 'shopping#update'
  end
  scope :shopping do
    put :add_to_list, to: 'shopping#add_to_list'
  end

  resources :shopping_list_items, only: [:destroy]

  resources :audits, only: [:index, :show, :update, :destroy]

  resources :reagent_categories, only: [:index, :show, :edit, :update, :new, :create]

  resources :reference_bottles, only: [:new, :create, :edit, :update, :destroy]
end

app/controllers/shared_cocktails_controller.rb
# TODO: this controller shares a frustrating amount of logic with the authed cocktails controller
class SharedCocktailsController < ApplicationController
  before_action :authenticate_user!, only: [:add_to_account]

  before_action :set_cocktail, only: [:show, :destroy]

  def index
    search_term = search_params['search_term']
    @tags_search = search_params['search_tags']
    makeable_enabled = search_params['makeable'].present? && search_params['makeable'] == 'on'

    initial_scope = Recipe.for_user(nil).where(category: 'cocktail')

    # force lookup for non-user mapped cocktails
    if search_term.present? && search_term.size > 0
      initial_scope = initial_scope.where('name ILIKE ?', "%#{search_term}%")
    end

    if @tags_search.present? && @tags_search.size > 0
      initial_scope = initial_scope.by_tag(*Array.wrap(@tags_search))
    end

    @availability = CocktailAvailabilityService.new(initial_scope, current_user)
    if makeable_enabled && user_signed_in?
      initial_scope = initial_scope.where(id: @availability.makeable_ids)
    end

    @reagent_categories = ReagentCategory.where(external_id: initial_scope.flat_map(&:tags)).order(:name)
    @cocktails = initial_scope.order(:name).page(params[:page])
    @dead_end = @cocktails.count <= 0 && @tags_search.present? ? true : false

    if user_signed_in? && current_user.admin?
      @proposal_cocktails = Recipe.where(category: 'cocktail').where('extras @> ?', { proposed_to_be_shared: true }.to_json)
    end

    # WIP faceting logic below here (pretty sure there's some sql injection in all this)
    raw_sql = "select word, ndoc from ts_stat($$ #{initial_scope.select(:searchable).to_sql} $$) order by ndoc desc;"
    if initial_scope.pluck(:id).count > 0
      raw_facets = ActiveRecord::Base.connection.execute(raw_sql)
      @processed_facets = raw_facets.entries.index_by { |f| f['word'] }
    else
      @processed_facets = {}
    end
  end

  def show
    @stats = {
      made_count: Audit.for_user(current_user).where(recipe: @cocktail).count,
      made_globally_count: Audit.where(recipe: @cocktail).count
    }
    @favorite = @cocktail.cocktail_families.include?(CocktailFamily.users_favorites(current_user))
    @shopping_lists = ShoppingList.for_user(current_user) || []
    # this is insane, but it sorta works. The goal is to see if the user
    # has any reagents in their shopping lists which fulfill a particular
    # set of tags. this does that I think
    @existing_shopping_list_map = @cocktail.reagent_amounts.map { |amount| [amount.id, Reagent.for_user(current_user).with_tags(amount.tags).where.not(shopping_list: nil).pluck(:shopping_list_id)] }.to_h

    @users_recent_audits = Audit.for_user(current_user).where(recipe: @cocktail).order(created_at: :desc).limit(5)
    @community_renderable_audits = Audit.where.not(user: current_user).where(recipe: @cocktail).order(created_at: :desc).select { |audit| audit.notes.present? }
    @user_copies = Recipe.for_user(current_user).where(parent: @cocktail)
  end

  def destroy
    @cocktail.destroy if @cocktail.present?

    respond_to do |format|
      format.html { redirect_to '/shared_cocktails', alert: "#{@cocktail.name} deleted!" }
    end
  end

  def add_to_account
    @shared_cocktail = Recipe.find(params[:shared_cocktail_id])

    Recipe.transaction do
      @copied_cocktail = @shared_cocktail.dup
      @copied_cocktail.user_id = current_user.id
      @copied_cocktail.parent = @shared_cocktail
      @copied_cocktail.clear_ingredients
      @copied_cocktail.save!

      @shared_cocktail.reagent_amounts.each do |shared_amount|
        copied_amount = shared_amount.dup
        copied_amount.recipe_id = @copied_cocktail.id
        copied_amount.user_id = current_user.id
        
        copied_amount.save!

        @copied_cocktail << copied_amount.convert_to_blob
      end

      @copied_cocktail.save!
    end

    respond_to do |format|
      format.turbo_stream
      format.json { render json: { action: 'add_to_account', cocktail_name: shared_cocktail.name.html_safe } }
    end
  end

  def promote_to_shared
    cocktail = Recipe.find(params[:shared_cocktail_id])

    Recipe.transaction do
      cocktail.proposed_to_be_shared = false
      cocktail.proposer_user_id = nil
      cocktail.save!

      copied_cocktail = cocktail.dup
      copied_cocktail.user_id = nil
      copied_cocktail.proposed_to_be_shared = false
      copied_cocktail.parent_id = nil
      copied_cocktail.clear_ingredients
      copied_cocktail.save!

      cocktail.reagent_amounts.each do |shared_amount|
        copied_amount = shared_amount.dup
        copied_amount.recipe_id = copied_cocktail.id
        copied_amount.user_id = nil

        copied_amount.save!

        copied_cocktail << copied_amount.convert_to_blob
      end
      copied_cocktail.save!
    end

    respond_to do |format|
      format.html { redirect_to action: 'index' }
      format.json { render json: { action: 'promoted_to_shared' } }
    end
  end

  private

  def set_cocktail
    @cocktail = Recipe.find(params[:id])
  end

  def search_params
    params.permit(:search_term, :makeable, search_tags: [])
  end
end

app/views/shared_cocktails/_added_to_account_toast_body.html.erb
<div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-controller="toast" data-action="hidden.bs.toast->toast#remove">
  <div class="toast-header">
    <strong>Cheers!</strong>
  </div>
  <div class="toast-body">
    <span>
      <p><%= @shared_cocktail.name.html_safe %> added to your account!</p>
    </span>
  </div>
</div>

app/views/shared_cocktails/add_to_account.turbo_stream.erb
<%= turbo_stream.prepend "toastDestination", partial: 'added_to_account_toast_body' %>

<%= turbo_stream.append "usersVersions" do %>
  <li>
    <%= link_to @copied_cocktail.name.html_safe, cocktail_path(@copied_cocktail) %>
  </li>
<% end %>

app/views/shared_cocktails/index.html.erb
<% content_for :per_page_js do %>
  <%= javascript_pack_tag "shared_cocktails_index", "data-turbo-track": 'reload' %>
<% end %>
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <%= form_with(url: "/shared_cocktails", method: "GET") do |form| %>
          <div class="field mb-1">
            <%= form.label :search_term, class: "form-label" %>
            <%= form.text_field :search_term, class: "form-control", value: params['search_term'] %>
          </div>

          <div class="field mb-2">
            <%= form.label :ingredient_search, class: "form-label" %>
            <select class="form-select ingredient-select" name="search_tags[]" multiple="multiple" data-controller="tag-selector">
              <% @reagent_categories.each do |reagent_category| %>
                <option value=<%= reagent_category.external_id %><% if params['search_tags'].present? && params['search_tags'].include?(reagent_category.external_id) %> selected<% end %>><%= reagent_category.external_id %></option>
              <% end %>
            </select>
            <div class="form-text">This is an AND query, which will contain only matching ingredients as you click "Search"</div>
          </div>

          <% if user_signed_in? %>
          <div class="form-check form-switch">
            <input class="form-check-input" type="checkbox" role="switch" id="makeableSwitch" name="makeable" <% if params['makeable'] == 'on' %>checked<% end %>>
            <label class="form-check-label" for="makeableSwitch">Only Drinks I can make now</label>
          </div>
          <% end %>

          <hr>
          <div>
            <span>Facets</span>
            <button class="btn btn-outline-info btn-sm mb-1" type="button" data-bs-toggle="collapse" data-bs-target=".facets-collapse" aria-expanded="false">Show Facets</button>
          </div>

          <div>
            <div style="max-height:70vh" class="collapse facets-collapse overflow-auto">
              <ul>
              <% @processed_facets.each do |tag, count| %>
                <li>
                  <button
                    type="button"
                    class="btn btn-outline-primary btn-sm mb-1"
                    data-controller="facets"
                    data-action="click->facets#clicked"
                    data-tag=<%= tag.gsub('/', '_') %>
                  >
                    <%= tag.gsub('/', '_') %> <span class="badge bg-secondary"><%= count['ndoc'] %><span>
                  </button>
                </li>
              <% end %>
              </ul>
            </div>
          </div>
          <hr>

          <div class="action mb-1">
            <%= form.submit "Search", class: "btn btn-primary" %>
            <% if request.query_string.present? %>
            <%= link_to 'Reset Search', shared_cocktails_path, class: "btn btn-danger" %>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="col-sm-9">
      <%= render 'shared/cocktails_table', cocktails: @cocktails, read_only: true, render_counts: user_signed_in? %>
      <% if @dead_end %>
      <p>Your combination of "<%= @tags_search.join(', ') %>" resulted in zero cocktails which have all those ingredients. Click "reset" to clear your search</p>
      <% end %>
      </div>
    </div>

    <% if user_signed_in? && current_user.admin? %>
      <hr>
      <p>Review these cocktails for addition to the shared list</p>
      <div class="col-sm">
        <div class="table-responsive">
          <table class="table" id="cocktailsTable">
            <thead>
              <tr>
                <th>Name</th>
                <th>Ingredients</th>
                <th>Accept into shared?</th>
              </tr>
            </thead>
            <tbody>
              <% @proposal_cocktails.each do |cocktail| %>
                <tr>
                  <td><%= cocktail.name.html_safe %></td>
                  <td>
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Ingredient</th>
                          <th>Amounts</th>
                        </tr>
                      </thead>
                      <tbody>
                        <% cocktail.reagent_amounts.each do |amount| %>
                          <tr>
                            <td>
                              <samp>
                                <% amount.tags.each_with_index do |tag, i| %>
                                  <%= tag %><% if i != amount.tags.size - 1 %><span>, </span><% end %>
                                <% end %>
                              </samp>
                            </td>
                            <td>
                              <%= amount.required_volume %>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </td>
                  <td><%= link_to "Accept", shared_cocktail_promote_to_shared_path(cocktail), method: "post", class: "btn btn-outline-success", data: { cocktail_id: cocktail.id } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>
  </div>
</main>

app/views/shared_cocktails/show.html.erb
<% content_for :per_page_js do %>
  <%= javascript_pack_tag "shared_cocktail_show", "data-turbo-track": 'reload' %>
<% end %>
<main>
  <div class="container">
    <%= render 'shared/notice' %>

    <div class="row mt-3">
      <div class="col-sm-3">
        <p>
          <strong>Name:</strong>
          <%= @cocktail.name.html_safe %>
        </p>
        <% if user_signed_in? %>
          <% if @cocktail.cocktail_families.exists? %>
          <span>
            <strong>Families:</strong>
            <ul>
            <% @cocktail.cocktail_families.each do |family| %>
              <li><%= link_to family.name, cocktail_family_path(family) %></li> 
            <% end %>
            </ul>
          </span>
          <% end %>
          <p>
            <strong>Favorite?:</strong>
            <% if @favorite %>
              <%= link_to "Remove Favorite", cocktail_toggle_favorite_path(@cocktail), class: "btn btn-outline-primary", method: "post" %>
            <% else %>
              <%= link_to "Favorite", cocktail_toggle_favorite_path(@cocktail), class: "btn btn-outline-primary", method: "post" %>
            <% end%>
          </p>
        <% else %>
          <% if @cocktail.global_cocktail_families.exists? %>
          <span>
            <strong>Families:</strong>
            <ul>
            <% @cocktail.global_cocktail_families.each do |family| %>
              <li><%= link_to family.name, cocktail_family_path(family) %></li> 
            <% end %>
            </ul>
          </span>
          <% end %>
        <% end %>
      </div>
      <div class="col">
        <strong>Cocktail Stats:</strong>
        <% if user_signed_in? %>
        <p>You've made this drink <span id="made_count"><%= @stats[:made_count] %></span> times!</p>
        <% end %>
        <p>All Barkeep users have made this drink <span id="made_globally_count"><%= @stats[:made_globally_count] %></span> times!</p>
      </div>

      <div class="col">
        <%= render 'shared/user_notes_table', audits: @users_recent_audits %>
        <div class="m-3">
          <strong>Community notes:</strong>
          <button class="btn btn-outline-info btn-sm" type="button" data-bs-toggle="collapse" data-bs-target=".community-audits-collapse" aria-expanded="false">Toggle Notes</button>
        </div>
        <div class="table-responsive collapse community-audits-collapse card card-body">
          <table class="table">
            <thead>
              <tr>
                <th>Stars</th>
                <th>Notes</th>
              </tr>
            </thead>
            <tbody>
              <% @community_renderable_audits.each do |audit| %>
              <tr>
                <td><%= audit.star_count %></td>
                <td><%= audit.notes %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <hr>

    <p>
      <strong>Ingredients:</strong>
    </p>

    <%= turbo_frame_tag(@cocktail) do %>
    <%= render 'shared/full_ingredients_table', cocktail: @cocktail %>
    <% end %>

    <% if user_signed_in? %>
      <p>You've promoted this cocktail into your list:</p>
      <ul id="usersVersions">
        <% @user_copies.each do |copy| %>
          <li>
            <%= link_to copy.name.html_safe, cocktail_path(copy) %>
          </li>
        <% end %>
      </ul>
      <%= link_to 'Promote to your list', shared_cocktail_add_to_account_path(@cocktail), class: "btn btn-primary", id: 'promote_link', method: :post %>
    <% else %>
      <strong>Create an account and sign in to see if you can make this cocktail!</strong>
    <% end %>
    <% if user_signed_in? && current_user.admin? %>
    <%= link_to 'Delete', shared_cocktail_path(@cocktail), class: "btn btn-danger", method: 'delete', data: { confirm: 'Are you sure you want to delete this cocktail?' } %>
    <% end %>

    <% if user_signed_in? %>
      <%= render 'shared/made_this_modal' %>
      <p class="mt-3">
        <% if @cocktail.user_can_make?(current_user) %>
        <span>You can make this drink! If you want to, click here:</span>
        <%= link_to 'Make Drink', drink_making_path(@cocktail), class: 'btn btn-success', data: { turbo_frame: 'madeThisModalFrame' } %>
        <% end %>
        <%= link_to 'Make Drink (with a twist)', drink_making_path(@cocktail, twist_mode: true), class: 'btn btn-success', data: { turbo_frame: 'madeThisModalFrame' } %>
      </p>
    <% end %>
    <%= render 'shared/reagents_guide' %>
    <%= render 'shared/similar_cocktails', cocktail: @cocktail %>

    <%= render 'shared/error_toast' %>
    <%= render 'shared/cheers_toast' %>
</main>