config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :audits
    resources :reagents
    resources :reagent_amounts
    resources :reagent_categories
    resources :recipes
    resources :reference_bottles
    resources :cocktail_families

    root to: "users#index"
  end
  devise_for :users
  root to: 'home#index'
  resources :recipes
  resources :reagents do
    post :refill
    post :empty
    get :add_to_list, to: 'reagents#shopping_list_show'
  end
  resources :bulk_reagents, only: [:index, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails do
    post :delete
    get :pre_make_drink
    post :make_drink
    post :toggle_favorite
    post :propose_to_share
    post :make_permanent
    get :nearest_neighbors
  end

  resources :cocktail_families, only: [:show, :create, :update]

  resources :drink_making, only: [:show, :update] do
  end

  # TODO: rename these routes
  scope :cocktails_async do
    get :drink_builder, to: 'cocktails#drink_builder'
  end

  resources :shared_cocktails, only: [:index, :show, :destroy] do
    post :add_to_account
    post :promote_to_shared
  end

  resources :shopping, only: [:index, :show, :new, :create, :destroy, :edit] do
    get :list
    post :purchase
    patch :list, to: 'shopping#update'
  end
  scope :shopping do
    put :add_to_list, to: 'shopping#add_to_list'
  end

  resources :shopping_list_items, only: [:destroy]

  resources :audits, only: [:index, :show, :update, :destroy]

  resources :reagent_categories, only: [:index, :show, :edit, :update, :new, :create]

  resources :reference_bottles, only: [:new, :create, :edit, :update, :destroy]
end

app/views/shared/_add_to_shopping_list_modal.html.erb
<div
  class="modal fade"
  tabindex="-1"
  id="addToShoppingListModal"
  aria-labelledby="addToShoppingListModalLabel"
  aria-hidden="true"
  data-controller="modal"
  data-action="turbo:frame-load->modal#open turbo:submit-end->modal#close"
>
  <div class="modal-dialog">
    <div class="modal-content">
    <%= turbo_frame_tag 'addToShoppingListModalFrame' do %>
      <div>Loading...</div>
    <% end %>
    </div>
  </div>
</div>

app/views/shared/_add_to_shopping_list_modal_body.html.erb
<%= turbo_frame_tag('addToShoppingListModalFrame') do %>
<div class="modal-header">
  <h5 class="modal-title" id="ModalTitle">Choose a list to add this bottle to:</h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
  <%= form_with(url: add_to_list_path, method: 'PUT', id: "addToShoppingListForm", data: { controller: 'ingredients-select' }) do |form| %>
    <%= form.text_field 'list_update[existing_bottle_id]', value: @reagent.id, hidden: true %>
    <div class="input-group">
      <%= form.collection_select(
          'list_update[shopping_list_id]',
          @shopping_lists,
          :id,
          :name,
          {
            include_blank: true,
            selected: @existing_shopping_list_map
          },
          {
            id: "shopping_select_",
            class: 'form-select',
            multiple: 'multiple',
            data: {
              'ingredients-select-target': 'select'
            }
          }
        ) %>
    </div>
  <% end %>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
  <input type="submit" class="btn btn-primary" form="addToShoppingListForm" value="Add to shopping lists!" />
</div>
<% end %>

app/views/shared/_cheers_toast.html.erb
<div class="toast-container position-fixed bottom-0 end-0 p-3" id="toastDestination" style="z-index: 11">
</div>

app/views/shared/_cheers_toast_body.html.erb
<div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-controller="toast" data-action="hidden.bs.toast->toast#remove">
  <div class="toast-header">
    <strong>Cheers!</strong>
  </div>
  <div class="toast-body">
    <span>
      <p><%= @cocktail.name.html_safe %> made!</p>
      <p>Reagents used:</p>
      <ul>
        <% @used_reagents.each do |reagent| %>
          <li><%= reagent[:used_model].name %></li>
        <% end %>
      </ul>
    </span>
    <span>
      <%= link_to "Leave a note here!", audit_path(@audit) %>
    </span>
  </div>
</div>

app/views/shared/_cocktails_table.html.erb
<div class="table-responsive">
  <table class="table" id="cocktailsTable">
    <thead>
      <tr>
        <th>Name</th>
        <% if render_counts %>
        <th>Count of reagents available</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% cocktails.each do |cocktail| %>
        <tr id="cocktail_<%= cocktail.id %>" <% if cocktail.user_id.blank? %> class="table-secondary"<% end %>>
          <% if cocktail.user_id.present? %>
          <td><%= link_to cocktail.name.html_safe, cocktail_path(cocktail) %></td>
          <% else %>
          <td><%= link_to cocktail.name.html_safe, shared_cocktail_path(cocktail) %></td>
          <% end %>
          <% if render_counts %>
          <td id="cocktail_<%= cocktail.id %>_count_row"><%= "#{@availability.available_counts[cocktail.id][:available]} of #{@availability.available_counts[cocktail.id][:required]}" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate cocktails %>

app/views/shared/_error_toast.html.erb
<div class="toast-container position-fixed bottom-0 end-0 p-3" id="errorToastDestination" style="z-index: 11">
</div>

<div data-toast-error-template class="toast" role="alert" aria-live="assertive" aria-atomic="true">
  <div class="toast-header">
    <i class="bi-exclamation-circle m-2" style="font-size: 1rem; color: red;" ></i>
    <strong>There was an error</strong>
  </div>
  <div class="toast-body">
    <span data-toast-body></span>
  </div>
</div>

app/views/shared/_full_ingredients_table.html.erb
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Tags</th>
        <th>Required Volume</th>
        <th>Detail</th>
        <th>Your bottles</th>
        <th>Add to shopping list</th>
      </tr>
    </thead>
    <tbody>
      <% cocktail.reagent_amounts.each do |reagent_amount| %>
        <% availability = reagent_amount.reagent_availability(current_user) %>
        <tr <% if availability.any? { |a| a[:garnish] } %> class="table-info"<% elsif availability.any? { |a| a[:enough] } %> class="table-success"<% elsif availability.present? %> class="table-warning"<% end %>>
          <td>
            <samp>
              <% reagent_amount.tags.each_with_index do |tag, i| %>
                <%= link_to tag, reagent_category_path(tag), data: { turbo_frame: '_top' } %><% if i != reagent_amount.tags.size - 1 %><span>, </span><% end %>
              <% end %>
            </samp>
          </td>
          <td><%= "#{reagent_amount.amount} #{reagent_amount.unit}" %></td>
          <td><%= reagent_amount.description %></td>
          <td>
            <% if user_signed_in? %>
            <%= reagent_amount.matching_reagents(current_user).has_volume.map { |bottle| link_to("#{bottle.name} (#{Lib.format_volume(bottle.current_volume, reagent_amount.unit)})", reagent_path(bottle), data: { turbo_frame: '_top' })}.join('<span>, </span>').html_safe %>
            <% else %>
            <span>Create an account to see your bottles here!</span>
            <% end %>
          </td>
          <td>
            <%= render 'shared/shopping_form', reagent_amount: reagent_amount, shopping_lists: @shopping_lists, existing_shopping_list_map: @existing_shopping_list_map %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/shared/_made_this_modal.html.erb
<div
  class="modal fade"
  id="madeThisModal"
  tabindex="-1"
  aria-labelledby="madeThisModalLabel"
  aria-hidden="true"
  data-controller="modal"
  data-action="turbo:frame-load->modal#open turbo:submit-end->modal#close"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalTitle">Let's make a drink!</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= turbo_frame_tag 'madeThisModalFrame' do %>
        <div>Loading...</div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_notice.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_propose_to_share_toast_body.html.erb
<div class="toast" role="alert" aria-live="assertive" aria-atomic="true" data-controller="toast" data-action="hidden.bs.toast->toast#remove">
  <div class="toast-header">
    <strong>Cheers!</strong>
  </div>
  <div class="toast-body">
    <span>
      <p>Thanks for your submission!</p>
      <p>We'll consider it for the shared cocktails list!</p> 
    </span>
  </div>
</div>

app/views/shared/_reagents_guide.html.erb
<div class="mb-3">
  <span>This guide will help explain the table above:</span>
  <button class="btn btn-info" type="button" data-bs-toggle="collapse" data-bs-target=".reference-collapse" aria-expanded="false">Toggle Legend</button>
</div>
<div class="table-responsive collapse reference-collapse card card-body">
  <table class="table">
    <thead>
      <tr>
        <th>Tags</th>
        <th>Required Volume</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><samp>Example Tag</samp></td>
        <td>White rows like this are tags with no matching bottles in <a href="/reagents">your collection</a></td>
      </tr>
      <tr class="table-warning">
        <td><samp>Example Tag</samp></td>
        <td>Yellow rows like this are tags where you have a bottle that matches, but not enough volume</td>
      </tr>
      <tr class="table-success">
        <td><samp>Example Tag</samp></td>
        <td>Green rows like this are tags where you have a bottle that matches, and enough volume. If all rows are green, you'll see a "Make Drink" button here instead</td>
      </tr>
      <tr class="table-info">
        <td><samp>Example Tag</samp></td>
        <td>Blue rows like this are optional, which we assume you always have (or could skip)</td>
      </tr>
    </tbody>
  </table>
</div>

app/views/shared/_shopping_form.html.erb
<% if user_signed_in? %>
  <%= form_with(url: add_to_list_path, method: 'PUT', data: { controller: 'ingredients-select' }) do |form| %>
    <%= form.text_field 'list_update[bottle_tags]', value: reagent_amount.to_placeholder_id, hidden: true %>
    <div class="input-group">
      <%= form.collection_select(
          'list_update[shopping_list_id]',
          shopping_lists,
          :id,
          :name,
          {
            include_blank: true,
            selected: existing_shopping_list_map[reagent_amount.id]
          },
          {
            id: "shopping_select_#{reagent_amount.to_placeholder_id}",
            class: 'form-select',
            multiple: 'multiple',
            data: {
              'ingredients-select-target': 'select'
            }
          }
        ) %>

      <%= form.submit "save", class: 'btn btn-primary' %>
    </div>
  <% end %>
<% else %>
<span>Create an account to start a shopping list!</span>
<% end %>

app/views/shared/_similar_cocktails.html.erb
<% if current_user.present? && current_user.admin? %>
<div>
  <%= link_to "Show similar cocktails", cocktail_nearest_neighbors_path(cocktail), data: { turbo_frame: "cocktail_#{cocktail.id}_neighbors" } %>

  <%= turbo_frame_tag("cocktail_#{cocktail.id}_neighbors") do %>
  <% end %>
</div>
<% end %>

app/views/shared/_user_notes_table.html.erb
<div class="m-3">
  <strong>Your recent notes:</strong>
  <button class="btn btn-outline-info btn-sm" type="button" data-bs-toggle="collapse" data-bs-target=".audits-collapse" aria-expanded="false">Toggle Notes</button>
</div>
<div class="table-responsive collapse audits-collapse card card-body">
  <table class="table">
    <thead>
      <tr>
        <th>Date</th>
        <th>Stars</th>
        <th>Notes</th>
      </tr>
    </thead>
    <tbody id="userNotesTableBody">
      <% audits.each do |audit| %>
      <tr>
        <td><%= link_to audit.created_at.strftime("%B %d, %Y"), audit_path(audit) %></td>
        <td><%= audit.star_count %></td>
        <td><%= audit.notes || 'no notes' %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>