config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :audits
    resources :reagents
    resources :reagent_amounts
    resources :reagent_categories
    resources :recipes
    resources :reference_bottles
    resources :cocktail_families

    root to: "users#index"
  end
  devise_for :users
  root to: 'home#index'
  resources :recipes
  resources :reagents do
    post :refill
    post :empty
    get :add_to_list, to: 'reagents#shopping_list_show'
  end
  resources :bulk_reagents, only: [:index, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails do
    post :delete
    get :pre_make_drink
    post :make_drink
    post :toggle_favorite
    post :propose_to_share
    post :make_permanent
    get :nearest_neighbors
  end

  resources :cocktail_families, only: [:show, :create, :update]

  resources :drink_making, only: [:show, :update] do
  end

  # TODO: rename these routes
  scope :cocktails_async do
    get :drink_builder, to: 'cocktails#drink_builder'
  end

  resources :shared_cocktails, only: [:index, :show, :destroy] do
    post :add_to_account
    post :promote_to_shared
  end

  resources :shopping, only: [:index, :show, :new, :create, :destroy, :edit] do
    get :list
    post :purchase
    patch :list, to: 'shopping#update'
  end
  scope :shopping do
    put :add_to_list, to: 'shopping#add_to_list'
  end

  resources :shopping_list_items, only: [:destroy]

  resources :audits, only: [:index, :show, :update, :destroy]

  resources :reagent_categories, only: [:index, :show, :edit, :update, :new, :create]

  resources :reference_bottles, only: [:new, :create, :edit, :update, :destroy]
end

app/models/reagent.rb
# == Schema Information
#
# Table name: reagents
#
#  id                   :bigint           not null, primary key
#  name                 :string
#  cost                 :decimal(, )
#  purchase_location    :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  description          :text
#  user_id              :bigint
#  max_volume_unit      :string           not null
#  max_volume_value     :decimal(10, 2)   not null
#  current_volume_value :decimal(10, 2)   not null
#  current_volume_unit  :string           not null
#  external_id          :string           not null
#  tags                 :string           default([]), is an Array
#  shopping_list_id     :bigint
#
# Indexes
#
#  index_reagents_on_external_id_and_user_id  (external_id,user_id) UNIQUE
#  index_reagents_on_name_and_user_id         (name,user_id) UNIQUE
#  index_reagents_on_shopping_list_id         (shopping_list_id)
#  index_reagents_on_user_id                  (user_id)
#

class Reagent < ApplicationRecord
  include UserScopable
  include Taggable

  scope :real, -> { where(shopping_list_id: nil) }
  scope :has_volume, -> { where('current_volume_value > 0') }

  belongs_to :shopping_list, optional: true

  measured Measured::Volume, :max_volume
  measured Measured::Volume, :current_volume

  validates :name, uniqueness: { scope: :user_id }
  validates :external_id, uniqueness: { scope: :user_id }

  validates :max_volume, measured: true
  validates :current_volume, measured: true

  def subtract_usage(amount)
    new_current = current_volume - amount

    if new_current.value <= 0.0
      update!(current_volume_value: 0)
    else
      update!(current_volume_value: new_current.value)
    end
  end

  # separate methods for this is dumb, yes
  def add_usage(amount)
    new_current = current_volume + amount

    update!(current_volume_value: new_current.value)
  end

  def unitless?
    max_volume_unit == 'unknown'
  end
end

app/controllers/admin/reagents_controller.rb
module Admin
  class ReagentsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/reagents_controller.rb
class ReagentsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_reagent, only: [:show, :edit, :update, :destroy]

  BASIC_BOTTLES = [:lime_juice, :lemon_juice, :whiskey, :gin, :soda_water]

  def index
    search_term = search_params['search_term']
    tags_search = search_params['search_tags']
    show_empty = search_params['show_empty'] == 'on'

    initial_scope = Reagent.for_user(current_user).where(shopping_list: nil)

    if search_term.present? && search_term.size > 0
      initial_scope = initial_scope.where('name ILIKE ?', "%#{search_term}%")
    end

    if tags_search.present?
      initial_scope = initial_scope.with_tags(tags_search)
    end

    initial_scope = initial_scope.has_volume if !show_empty

    @reagents = initial_scope.order(:name)

    existing_basics = Reagent.for_user(current_user).with_tags(BASIC_BOTTLES).flat_map(&:tags).map(&:to_sym)
    @basics_missing = (BASIC_BOTTLES - existing_basics).map do |basic_tag|
      {
        name: basic_tag.to_s.titleize,
        tags: [basic_tag]
      }
    end

    available_tags = @reagents.pluck(:tags).flatten.uniq
    @reagent_categories = ReagentCategory.where(external_id: available_tags).order(:name)
  end

  def new
    @reagent = Reagent.new(user_id: current_user.id, max_volume_value: 750, current_volume_value: 750)
    @reagent_categories = ReagentCategory.all.order(:name)
    @possible_units = POSSIBLE_UNITS_ML
  end

  def show
    amounts = ReagentAmount.for_user_or_shared(current_user).with_tags(@reagent.tags)
    @cocktails = Recipe.where(id: amounts.pluck(:recipe_id)).page(params[:page])
    @availability = CocktailAvailabilityService.new(@cocktails, current_user)
  end

  def shopping_list_show
    @reagent = Reagent.for_user(current_user).find(params[:reagent_id])
    @shopping_lists = ShoppingList.for_user(current_user)
    @existing_shopping_list_map = Reagent.for_user(current_user).with_tags(@reagent.tags).pluck(:shopping_list_id).uniq.compact
  end

  def edit
    @possible_units = POSSIBLE_UNITS_ML
  end

  def refill
    # I don't know why this route sends the id as "reagent_id" instead of "id". probably some nested route magic
    reagent = Reagent.for_user(current_user).find_by(id: params['reagent_id'])
    reagent.update!(current_volume: reagent.current_volume + reagent.max_volume) if reagent.present?

    respond_to do |format|
      format.html { redirect_to reagent, notice: "#{reagent.name} refilled" }
      format.json do
        render json: {
          action: 'refill',
          reagent_id: reagent.id,
          new_volume: reagent.current_volume,
          reagent_name: reagent.name
        }
      end
    end
  end

  def empty
    reagent = Reagent.for_user(current_user).find_by(id: params['reagent_id'])
    reagent.update!(current_volume_value: 0) if reagent.present?

    respond_to do |format|
      format.html { redirect_to reagent, notice: "#{reagent.name} emptied" }
      format.json do
        render json: {
          action: 'empty',
          reagent_id: reagent.id,
          new_volume: reagent.current_volume,
          reagent_name: reagent.name
        }
      end
    end
  end

  def create
    parsed_params = parse_and_maybe_create_category(reagent_params)
    @reagent = Reagent.for_user(current_user).new(parsed_params.except(:redirect_path))
    @reagent_categories = ReagentCategory.all.order(:name)
    @possible_units = POSSIBLE_UNITS_ML

    respond_to do |format|
      if @reagent.save
        if params[:commit] == "Create Bottle and add another"
          format.html { redirect_to new_reagent_path, notice: "#{@reagent.name} was successfully created" }
        else
          # TODO: handle the notice
          format.html { redirect_to @reagent, notice: "#{@reagent.name} was successfully created" }
        end
      else
        format.html { render :new, status: :unprocessable_entity, notice: "Errors creating your bottle: #{@reagent.errors.first(5)}" }
      end
    end
  end

  def update
    parsed_params = parse_and_maybe_create_category(reagent_params)
    redirect_path = parsed_params.delete(:redirect_path)
    @possible_units = POSSIBLE_UNITS_ML

    respond_to do |format|
      if @reagent.update(parsed_params)
        if redirect_path.present?
          format.html { redirect_to redirect_path, notice: "#{@reagent.name} was successfully updated" }
        else
          format.html { redirect_to @reagent, notice: "#{@reagent.name} was successfully updated" }
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @reagent.destroy if @reagent.present?

    respond_to do |format|
      format.html { redirect_to '/reagents', alert: "#{@reagent.name} deleted!" }
    end
  end

  private

  def parse_and_maybe_create_category(params)
    params[:tags] = params[:tags].map(&:strip).map { |tag| Lib.to_external_id(tag) }

    params[:tags].each do |tag|
      ReagentCategory.find_or_create_by(external_id: tag) { |created_model| created_model.name = tag.titleize }
    end
    
    params[:external_id] = Lib.to_external_id(params[:name])

    params[:max_volume_unit] = params[:volume_unit]
    params[:current_volume_unit] = params[:volume_unit]
    params.delete(:volume_unit)

    params
  end

  def set_reagent
    # TODO: handle 404
    @reagent = Reagent.for_user(current_user).find(params[:id])
    @reagent_categories = ReagentCategory.all.order(:name)
  end

  def reagent_params
    # I bet we could pull this from the model, that would be cool
    params
      .require(:reagent)
        .permit(:name, :cost, :purchase_location, :max_volume_value, :current_volume_value, :volume_unit, :description, :redirect_path, tags: [])
  end

  def search_params
    params.permit(:search_term, :commit, :show_empty, search_tags: [])
  end
end

app/views/reagents/_form.html.erb
<% content_for :per_page_js do %>
  <%= javascript_pack_tag "reagents_form", "data-turbo-track": 'reload' %>
<% end %>

<%= form_with(model: reagent) do |form| %>
  <% if reagent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reagent.errors.count, "error") %> prohibited this reagent from being saved:</h2>

      <ul>
        <% reagent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :redirect_path, value: params[:redirect_path], hidden: true %>

  <div class="field mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control", value: params[:name] || reagent.name, required: true %>
  </div>

  <div class="field mb-3">
    <%= form.label :tags, class: "form-label" %>
    <select class="form-select ingredient-select" name="reagent[tags][]" multiple="multiple" required>
      <% @reagent_categories.each do |reagent_category| %>
        <option value=<%= reagent_category.external_id %><% if params[:tags]&.include?(reagent_category.external_id) || reagent.tags.include?(reagent_category.external_id) %> selected<% end %>><%= reagent_category.external_id %></option>
      <% end %>
    </select>
  </div>

  <div class="field mb-3">
    <%= form.label :max_volume, class: "form-label" %>
    <%= form.text_field :max_volume_value, class: "form-control", required: true %>
    <% if reagent.id.nil? %>
    <div class="form-text">Defaulted max volume and current volume values to 750 (a fifth). Change them if necessary!</div>
    <% end %>
  </div>

  <div class="field mb-3">
    <%= form.label :current_volume, class: "form-label" %>
    <%= form.text_field :current_volume_value, class: "form-control", required: true %>
  </div>

  <div class="field mb-3">
    <%= form.label :volume_unit, class: "form-label" %>
    <%= form.select :volume_unit, @possible_units.map { |unit| [ unit, unit ] }.to_h, { selected: reagent.max_volume_unit }, class: "form-select" %>
  </div>

  <div class="field mb-3">
    <%= form.label :cost, class: "form-label" %>
    <%= form.text_field :cost, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :purchase_location, class: "form-label" %>
    <%= form.text_field :purchase_location, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <% if reagent.id.blank? %>
  <div class="actions mb-3">
    <%= form.submit "Create Bottle", class: "btn btn-primary" %>
  </div>

  <div class="actions mb-3">
    <%= form.submit "Create Bottle and add another", class: "btn btn-outline-primary" %>
  </div>
  <% else %>
  <div class="actions mb-3">
    <%= form.submit "Update Bottle", class: "btn btn-primary" %>
  </div>
  <% end %>
<% end %>

app/views/reagents/edit.html.erb
<main>
  <div class="container">
    <%= render 'form', reagent: @reagent %>

    <%= link_to 'Back', reagent_path, class: "btn btn-danger" %>
  </div>
</main>

app/views/reagents/index.html.erb
<% content_for :per_page_js do %>
  <%= javascript_pack_tag "reagents", "data-turbo-track": 'reload' %>
<% end %>
<main>
  <div class="container">
    <%= render 'shared/notice' %>
    <div class="row">
      <div class="col-sm-3">
        <%= form_with(url: "/reagents", method: "GET") do |form| %>
          <div class="field mb-1">
            <%= form.label :search_term, class: "form-label" %>
            <%= form.text_field :search_term, class: "form-control", value: params['search_term'] %>
          </div>

          <div class="field mb-2">
            <%= form.label :ingredient_search, class: "form-label" %>
            <select class="form-select reagent-select" name="search_tags[]" multiple="multiple">
              <% @reagent_categories.each do |reagent_category| %>
                <option value=<%= reagent_category.external_id %><% if params['search_tags'].present? && params['search_tags'].include?(reagent_category.external_id) %> selected<% end %>><%= reagent_category.external_id %></option>
              <% end %>
            </select>
            <div class="form-text">This is an OR query</div>
          </div>

          <div class="form-check form-switch">
            <input class="form-check-input" type="checkbox" role="switch" id="showEmptySwitch" name="show_empty" <% if params['show_empty'] == 'on' %>checked<% end %>>
            <label class="form-check-label" for="showEmptySwitch">Show empty bottles</label>
          </div>

          <div class="action mb-1">
            <%= form.submit "Search", class: "btn btn-primary" %>
          </div>
        <% end %>
        <%= link_to 'New Bottle', new_reagent_path, class: 'btn btn-primary' %>
        <hr>
        <div class="form-text">Your bottle list is missing these common ingredients. Click below to quickly add them.</div>
        <% @basics_missing.each do |basic_model| %>
          <%= link_to "#{basic_model[:name]}", new_reagent_path(basic_model), class: 'btn btn-info mb-3' %>
        <% end %>
      </div>
      <div class="col-sm-9">
        <div class="table-responsive">
          <table class="table" id="reagentsTable">
            <thead>
              <tr>
                <th>name</th>
                <th>Tags</th>
                <th>Current Volume</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              <% @reagents.each do |reagent| %>
                <tr id="reagent_<%= reagent.id %>" <% if reagent.tags.blank? %> class="table-warning"<% end %>>
                  <td><%= link_to reagent.name, reagent_path(reagent) %></td>
                  <td>
                    <samp>
                      <% reagent.tags.each_with_index do |tag, i| %>
                        <%= link_to tag, reagent_category_path(tag) %><% if i != reagent.tags.size - 1 %><span>, </span><% end %>
                      <% end %>
                    </samp>
                    <% if reagent.tags.blank? %>
                      <span><small class="text-wrap">This bottle has no tags, so it can't be used in drinks</small></span>
                    <% end %>
                  </td>
                  <td data-volume-row><%= reagent.current_volume %></td>
                  <td>
                    <%= link_to "Refill", reagent_refill_path(reagent, format: 'json'), remote: true, method: "post", class: "btn btn-outline-success", data: { reagent_id: reagent.id, confirm: "Are you sure you want to refill #{reagent.name}?" } %>
                    <%= link_to "Empty", reagent_empty_path(reagent, format: 'json'), remote: true, method: "post", class: "btn btn-outline-danger", data: { reagent_id: reagent.id, confirm: "Are you sure you want to empty #{reagent.name}?" } %>
                    <%= link_to "Add To List", reagent_add_to_list_path(reagent), class: "btn btn-outline-info mt-1", data: { turbo_frame: 'addToShoppingListModalFrame' } %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <a href="/bulk_reagents" class="btn btn-info">Bulk import reagents</a>
      </div>
    </div>

    <%= render 'shared/add_to_shopping_list_modal' %>

    <div class="toast-container position-fixed bottom-0 end-0 p-3" id="toastDestination" style="z-index: 11">
    </div>

    <div data-toast-template class="toast" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-header">
        <strong>Watch out!</strong>
      </div>
      <div class="toast-body">
        <span data-toast-body></span>
      </div>
    </div>
  </div>
</main>

app/views/reagents/new.html.erb
<div class="container">
  <h1>New Reagent</h1>
  <%= render 'shared/notice' %>

  <%= render 'form', reagent: @reagent %>

  <%= link_to 'Back', reagents_path, class: "btn btn-info" %>
</div>

app/views/reagents/shopping_list_show.html.erb
<%= render 'shared/add_to_shopping_list_modal_body' %>

app/views/reagents/show.html.erb
<% content_for :per_page_js do %>
  <%= javascript_pack_tag "reagents_show", "data-turbo-track": 'reload' %>
<% end %>
<main>
  <div class="container">
    <%= render 'shared/notice' %>

    <p>
      <strong>Name:</strong>
      <%= @reagent.name %>
    </p>

    <p>
      <strong>Tags:</strong>
      <% if @reagent.tags.present? %>
        <samp>
          <% @reagent.tags.each_with_index do |tag, i| %>
            <%= link_to tag, reagent_category_path(tag) %><% if i != @reagent.tags.size - 1 %><span>, </span><% end %>
          <% end %>
        </samp>
      <% end %>
    </p>

    <p>
      <strong>Cost:</strong>
      <%= @reagent.cost %>
    </p>

    <p>
      <strong>Purchase Location:</strong>
      <%= @reagent.purchase_location %>
    </p>

    <p>
      <strong>Max Volume:</strong>
      <%= @reagent.max_volume %>
    </p>

    <p>
      <strong>Current Volume:</strong>
      <%= @reagent.current_volume %>
    </p>

    <%= link_to 'Edit', edit_reagent_path(@reagent), class: "btn btn-primary" %>
    <%= link_to 'Delete', reagent_path(@reagent), class: "btn btn-danger", method: 'delete', data: { confirm: 'Are you sure you want to delete this bottle?' } %>
    <% # Users should be able to easily see what shopping list a bottle is already in. They shouldn't have to click this %>
    <%= link_to "Add To List", reagent_add_to_list_path(@reagent), class: "btn btn-outline-info", data: { turbo_frame: 'addToShoppingListModalFrame' } %>
    <%= render 'shared/add_to_shopping_list_modal' %>

    <hr>
    <p>
      <strong>Cocktails which use this reagent</strong>
    </p>


    <%= render 'shared/cocktails_table', cocktails: @cocktails, read_only: true, render_counts: user_signed_in? %>
  </div>
</main>